### ISSUE TITLE
Memory management

### ISSUE THREAD

**Issue by axic** [ewasm/evm2wasm#16]
In order to support MSTORE/MLOAD we need to properly manage memory.

A simplistic approach is to allocate the first 32768 bytes of memory for the stack (stack limit is 1024 items, 256 bits each). The memory for MSTORE/MLOAD then starts from offset 32768.

Alternatively the opcodes themselves could have a parameter for memory offset. This should be calculated by the transcompiler.

**Comment by wanderer** [comment]
> This should be calculated by the transcompiler.

I'm not sure how the transcompiler would do this. it doesn't "know" how many items will be on the stack before each mem op

**Comment by axic** [comment]
@wanderer it could calculate the maximum stack depth and reserve enough memory for that.

It might be an unnecessary optimisation and perhaps the above fixed 32k is good enough.

**Comment by axic** [comment]
Additional memory needs to be set aside for operations like `CALLER`, `CALLVALUE`, etc.

**Comment by wanderer** [comment]
Memory Management is now basically done. It's still messed a bit b/c of v8 0xb
