### ISSUE TITLE
Produce an error when invalid EVM bytecode is provided

### ISSUE THREAD

**Issue by jwasinger** [ewasm/evm2wasm#223]
e.g: `./bin/evm2wasm.js asdfdsdf --trace` should result in an error.

**Comment by jalextowle** [comment]
Is this still an open issue? If so I would like to take a crack at it.

**Comment by jwasinger** [comment]
yup! go ahead.

**Comment by jalextowle** [comment]
Didn't see this until now, but I'll get on it.

**Comment by jwasinger** [comment]
For opcodes that aren't valid EVM opcodes, we can simply insert an `unreachable` statement into the produced wast.

**Comment by jwasinger** [comment]
In fact, this might be the current behavior.  Let me verify.

**Comment by jalextowle** [comment]
Sounds good. Thank you for all of the help

J. Alex Towle
Class of 2020

**Comment by jwasinger** [comment]
yup.. this is already the current behavior.  Thanks for your interest @jalextowle but this is a non-issue.
