### ISSUE TITLE
Option to generate EEI imports as a C++ file

### ISSUE THREAD

**Issue by jwasinger** [ewasm/evm2wasm#237]
[This](https://github.com/ewasm/evm2wasm/blob/master/wasm/generateInterface.js) should be modified to output a file like [this](https://github.com/lrettig/evm2wasm/blob/3db366d3059bd2d7ff5a63de059fd9fcef008128/include/wast.h) .

This should be done on: https://github.com/ewasm/evm2wasm/pull/201

**Comment by axic** [comment]
Done in #201.
